apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["mamad-namespace/fpm-test"]'
    management.cattle.io/ui-managed: "true"
  name: fpm-svc
  namespace: mamad-namespace
spec:
  ports:
  - name: fpm-port
    port: 9000
    protocol: TCP
    targetPort: 9000

  ## selector that match workload in rancher
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-mamad-namespace-fpm-test
  ##
  sessionAffinity: None
  type: ClusterIP